USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE MEDSYNC_WH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE DATABASE MEDSYNC_AI;

CREATE OR REPLACE SCHEMA MEDSYNC_AI.BRONZE;
CREATE OR REPLACE SCHEMA MEDSYNC_AI.SILVER;
CREATE OR REPLACE SCHEMA MEDSYNC_AI.GOLD;
CREATE OR REPLACE SCHEMA MEDSYNC_AI.AI;
CREATE OR REPLACE SCHEMA MEDSYNC_AI.OPS;

USE WAREHOUSE MEDSYNC_WH;
USE DATABASE MEDSYNC_AI;
USE SCHEMA OPS;

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE MEDSYNC_STAGE
FILE_FORMAT = CSV_FORMAT;